# Generated by Django 6.0 on 2025-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
