# Generated by Django 5.2.8 on 2025-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_certificado_id_alter_experiencia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_static',
            field=models.CharField(blank=True, help_text='img/dos.png', max_length=200),
        ),
    ]
