# Generated by Django 5.2.8 on 2025-12-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_proyecto_imagen_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_static',
            field=models.CharField(blank=True, help_text='Ruta dentro de static/, por ejemplo: img/proyecto1.png', max_length=200),
        ),
    ]
